import type { Project } from "@/lib/types";

export const placeholderProjects: Project[] = [
  {
    slug: "lime-house-bannerghatta",
    name: "Lime House, Bannerghatta",
    track: "traditional",
    type: "Residential house",
    area: "Bannerghatta Road, Bengaluru",
    status: "completed",
    year: "2023",
    cover: "/projects/placeholder/cover.jpg",
    gallery: [],
    highlights: ["Lime mortar masonry", "Madras Terrace roof", "Breathable interiors"],
    body: "TODO(Prakash): project narrative.",
    published: false,
  },
  {
    slug: "surkhee-villa-whitefield",
    name: "Surkhee Villa, Whitefield",
    track: "traditional",
    type: "Villa",
    area: "Whitefield, Bengaluru",
    status: "completed",
    year: "2023",
    cover: "/projects/placeholder/cover.jpg",
    gallery: [],
    highlights: ["Surkhee plastering", "Heritage detailing", "Traditional arches"],
    body: "TODO(Prakash): project narrative.",
    published: false,
  },
  {
    slug: "rcc-home-sarjapur",
    name: "RCC Home, Sarjapur",
    track: "modern",
    type: "Residential house",
    area: "Sarjapur Road, Bengaluru",
    status: "completed",
    year: "2024",
    cover: "/projects/placeholder/cover.jpg",
    gallery: [],
    highlights: ["RCC framed structure", "Turnkey delivery", "Landscaped garden"],
    body: "TODO(Prakash): project narrative.",
    published: false,
  },
  {
    slug: "townhouse-hsr",
    name: "Townhouse, HSR Layout",
    track: "modern",
    type: "Townhouse",
    area: "HSR Layout, Bengaluru",
    status: "completed",
    year: "2024",
    cover: "/projects/placeholder/cover.jpg",
    gallery: [],
    highlights: ["Modern exterior finishes", "Modular interiors", "Compact design"],
    body: "TODO(Prakash): project narrative.",
    published: false,
  },
  {
    slug: "heritage-restoration-basavanagudi",
    name: "Heritage Restoration, Basavanagudi",
    track: "traditional",
    type: "Heritage restoration",
    area: "Basavanagudi, Bengaluru",
    status: "ongoing",
    cover: "/projects/placeholder/cover.jpg",
    gallery: [],
    highlights: ["Lime plaster restoration", "Original material conservation", "Pre-independence structure"],
    body: "TODO(Prakash): project narrative.",
    published: false,
  },
  {
    slug: "madras-terrace-home",
    name: "Madras Terrace Home",
    track: "traditional",
    type: "Residential house",
    area: "Jayanagar, Bengaluru",
    status: "design",
    cover: "/projects/placeholder/cover.jpg",
    gallery: [],
    highlights: ["Madras Terrace roof", "Lime construction", "Passive cooling design"],
    body: "TODO(Prakash): project narrative.",
    published: false,
  },
];
